### ISSUE TITLE
[Fastlane] Info.plist from UnitTest target overrides values read from `config_file`

### ISSUE THREAD

**Issue by Burgestrand** [bugsnag/bugsnag-dsym-upload#11]
### Expected behavior
```ruby
send_build_to_bugsnag(config_file: application.info_plist_path)
```
Above code should read `appVersion` from the given `config_file`.

### Observed behavior
`appVersion` reported to bugsnag is taken from `UnitTests/Info.plist`.

### Steps to reproduce
1. Have a unit test target with an `Info.plist`.
2. Have an app target with a letter that begins with a letter later than U in the alphabet, (our case: V).
3. `send_build_to_bugsnag(config_file: "App/Info.plist")`

### Version
`fastlane-plugin-bugsnag (1.3.0)`

### Additional information
This happens because of two issues.

1. [`default_info_plist_path`](https://github.com/bugsnag/bugsnag-dsym-upload/blob/be109217a611ec49a34828c2026fced0a8f1bc8e/tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/send_build_to_bugsnag.rb#L201) is used despite providing a `config_file`, unfortunately `default_info_plist_path` returns the _wrong_ `Info.plist`.
2. The default plist path is used to populate the default `params`
3. Default `params` override any values from `config_file`-specified, due to the order they're read, see here: https://github.com/bugsnag/bugsnag-dsym-upload/blob/be109217a611ec49a34828c2026fced0a8f1bc8e/tools/fastlane-plugin/lib/fastlane/plugin/bugsnag/actions/send_build_to_bugsnag.rb#L10-L25

Code linked assumes that `params` are only explicitly set by the user, but `params` also contains default values, which happens to be provided by the `default_info_plist_path`, which in my particular case finds the _wrong_ `Info.plist` because `UnitTests/Info.plist` appears before our app `V/Info.plist` in directory listings.

**Comment by kattrali** [comment]
Thank you for the detailed report, @Burgestrand. I think there a few approaches we can take to improve the config file/params resolution.

1. Exclude test Info.plist files by default - there is already similar logic for Info.plist files found in `build` directories.
2. If `config_file` is changed from the default value, require API key, app version, and bundle version to be loaded from there. 

I've made a start on these changes which will go into a new patch release.

**Comment by Burgestrand** [comment]
Thanks! Yes, I believe __2__ would be enough to solve it in my specific case!

**Comment by kattrali** [comment]
Well, *1* should solve your specific case by automatically detecting the right Info.plist file more often. Ideally no one should ever have to set `config_file` at all :)

**Comment by Burgestrand** [comment]
Thank you for the Swift fix!

I just now found that the default search path for `default_info_plist_path` only goes a single level (I don't know why I didn't catch this before), and because of my `Info.plist` being buried 3 levels deep it's not included in the list at all (although when it is, it would still not have been the first one in the list so the fix was not in vain 😄).

It's not a problem for me due to your fix in _2_, but I felt it was worth mentioning. My directory structure looks like so:

```
.
├── UnitTests
│   └── Info.plist
├── VideoApp
│   ├── Application
│   │   └── Assets
│   │       └── Info.plist <~~~ Here it is!
│   └── … there's way more stuff here! …
├── VideoApp.playground
├── VideoApp.xcodeproj
├── VideoApp.xcworkspace
└── fastlane
```

**Comment by kattrali** [comment]
Thanks for the feedback @Burgestrand, the structure diagram is helpful. The intent behind only going a single level was to avoid catching Info.plist files from `Pods`, `Carthage/Build`, `build` artifacts, etc, though maybe this is something to consider as well. I'm glad the fix is working and will consider how we could better detect the config file for cases like this.
