### ISSUE TITLE
mktemp template needs XXX appended

### ISSUE THREAD

**Issue by philihp** [bugsnag/bugsnag-dsym-upload#14]
This isn't a problem when running on a macOS machine, but when running on a Linux machine it happens.

### Expected behavior
* Script should fail with an error code when failing to create a temp directory
* Replace:

        temp_dir=$(mktemp -dt "bugsnag-dsym-upload")
  with

        temp_dir=$(mktemp -dt "bugsnag-dsym-upload.XXX")

### Observed behavior

Reports successful upload
```
[22:57:12]: --- Step: upload_symbols_to_bugsnag ---
[22:57:12]: ---------------------------------------
mktemp: too few X's in template ‘bugsnag-dsym-upload’
error:  must specify directory to which to extract with -d option
Uploaded dSYMs in MyApp-18.13-dSYM.zip
```

### Steps to reproduce
Run the plugin action on a machine with gnu-mktemp (e.g. a linux machine). This can be confirmed with `mktemp --version`

```
Usage: mktemp [OPTION]... [TEMPLATE]
Create a temporary file or directory, safely, and print its name.
TEMPLATE must contain at least 3 consecutive 'X's in last component.
If TEMPLATE is not specified, use tmp.XXXXXXXXXX, and --tmpdir is implied.
Files are created u+rw, and directories u+rwx, minus umask restrictions.
```

**Comment by kattrali** [comment]
Thanks for the detailed report, @philihp. Supporting GNU mktemp is a straightforward change.
