### ISSUE TITLE
Move homebrew formula to separate formula tap

### ISSUE THREAD

**Issue by kylef** [bugsnag/bugsnag-dsym-upload#16]
The current steps to install via homebrew are as follows:

```shell
$ brew install https://raw.github.com/bugsnag/bugsnag-upload/master/tools/homebrew/bugsnag-dsym-upload.rb
```

Since this is via a direct URL to the formula, there is a downside that the version cannot be easily updated and upgraded via homebrew. I cannot do `brew update && brew upgrade` to update bugsnag-dsym-upload and I would end up keeping an older version so it is not easy to upgrade the package.

See https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md .

**Comment by kattrali** [comment]
Thanks for the report, @kylef. We should have a tap for all our homebrew formulae!

**Comment by ecerney** [comment]
This is now an issue in that homebrew does not allow installs from an arbitrary URL anymore. We cannot install `bugsnag-dsym-upload` in our bitrise flow:

```
$ brew "install" "https://raw.github.com/bugsnag/bugsnag-upload/master/tools/homebrew/bugsnag-dsym-upload.rb"
Error: Calling Non-checksummed download of bugsnag-dsym-upload formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
```

**Comment by steve-nester-uk** [comment]
@ecerney thanks for raising, we're going to take a look!

**Comment by xander-jones** [comment]
@ecerney We've moved this formula to a Homebrew tap 🎉​ .

If you have previously installed the bugsnag-dsym-upload tool, uninstall it with
```
$ brew uninstall bugsnag-dsym-upload
```

Clean up your local Homebrew area with
```
$ brew cleanup
```

Then, you can install `bugsnag-dsym-upload` with:
```
$ brew install bugsnag/tap/bugsnag-dsym-upload
```

This will also add the Bugsnag tap, so that any updates to the dSYM upload tool can be downloaded through Homebrew directly in future.

**Comment by ecerney** [comment]
Thanks @xander-jones and @steve-nester-uk for the quick look at this! We will test it out today in our CI and let you know if anything comes up.
