### ISSUE TITLE
Acute characters in CFBundleIdentifier causes upload to fail

### ISSUE THREAD

**Issue by argentounce** [bugsnag/bugsnag-dsym-upload#19]
### Expected behavior
Upload data

### Observed behavior
`error:  cannot create /var/folders/wh/w71drswxxxxxsb1jdd7v9v540000gp/T/bugsnag-dsym-upload.XXX.bIUl4wOG/A7660156-XXXX-3F45-A0AD-4F663D8585EE.dSYM/Contents/Resources/DWARF/+?ntima M+?vil`

### Steps to reproduce
Use a product name that uses acute characters

### Version
1.3.2

**Comment by kattrali** [comment]
Thank you for the report, @argentounce. Looking into it.

**Comment by xander-jones** [comment]
👋 . we've just released https://github.com/bugsnag/bugsnag-dsym-upload/releases/tag/v2.1.0 of the `bugsnag-dsym-upload` tool which which will now allow you to upload dSYMs with special characters in the pathname. I believe this should fix the issue that you were observing in this issue, but do let us know if you spot any problems.
