### ISSUE TITLE
Bugsnag API key not being found in Info.plist

### ISSUE THREAD

**Issue by bgold0** [bugsnag/bugsnag-dsym-upload#31]
### Expected behavior
It should send my build to bugsnag.

### Observed behavior

When running `send_build_to_bugsnag` in fastlane, I get the following error:
> A Bugsnag API key is required to release a build. Set BugsnagAPIKey in your Info.plist file to detect API key automatically.

### Steps to reproduce

- Insert BugsnagAPIKey in Info.plist like so:
    ```
    <dict>
       ...
       <key>BugsnagAPIKey</key>
       <string>1234567890</string>
    </dict>
    ```

- Run `send_build_to_bugsnag` in fastlane and you get that error.

**Comment by mattdyoung** [comment]
Hi @bgold0 

I'm unable to reproduce the behaviour you describe.

Could you contact support@bugsnag.com and provide a copy of:
- your `Fastfile`
- your `Info.plist`
- the full output you see when running the `send_build_to_bugsnag` action

Thanks!

**Comment by jaltin** [comment]
I am experiencing the same problem as you @bgold0. Did you find a solution?

**Comment by mattdyoung** [comment]
@bgold0 
If you're able to provide us with the details asked for above:
https://github.com/bugsnag/bugsnag-dsym-upload/issues/31#issuecomment-532186161
we'd be happy to investigate and advise on a way forward.

I'd recommend sending the details to support@bugsnag.com if there's anything sensitive in the config / output.

**Comment by bgold0** [comment]
@mattdyoung I'll reach out when I have some time but not sure what else there is to say that isn't said here. I'd be happy to provide more information as needed. I don't think a Fastlane file is necessary since running it directly from the terminal like so gives the same error:

`fastlane run send_build_to_bugsnag`

@jaltin I wasn't able to fix this but I ended up doing this instead:

	Dir.chdir("../..") do
	   workingDirectory = File.expand_path(File.dirname(__FILE__))
	   sh('mkdir build')
	   sh('react-native bundle --platform ios --dev false --entry-file ./index.js --bundle-output build/ios-release.bundle --sourcemap-output build/ios-release.bundle.map --assets-dest build')
	   sh("curl https://upload.bugsnag.com/react-native-source-map \ -F apiKey=#{bugsnagapikey} \ -F overwrite=true \ -F appVersion=#{version} \ -F platform=ios \ -F sourceMap=@build/ios-release.bundle.map \ -F bundle=@build/ios-release.bundle")
	   sh ('rm -rf build')
	end

**Comment by mattdyoung** [comment]
Hi @bgold0 

Thanks for the info. We're currently unable to reproduce this issue at all, but if you can supply us with any minimal but complete example project which demonstrates the issue we can try that out to see if we can reproduce here.

Is the `send_build_to_bugsnag` action definitely picking up the correct `Info.plist`? Can you try specifying explicitly using the `config_file` option?

**Comment by cwhenderson20** [comment]
I'm also seeing this behavior. My Fastfile is nothing special:

```ruby
default_platform(:ios)

platform :ios do
  desc 'Distribute a new beta build'
  lane :beta do
    build_number = sh('../../scripts/version/versions.sh')
    increment_build_number(
      build_number: build_number
    )
    build_ios_app
    upload_to_testflight
    upload_symbols_to_bugsnag
    send_build_to_bugsnag
  end
end
```

The output from the final `send_build_to_bugsnag` command is simply:
```
[01:31:24]: A Bugsnag API key is required to release a build. Set BugsnagAPIKey in your Info.plist file to detect API key automatically.
```

As previously mentioned, `BugsnagAPIKey` is definitely set in the Info.plist (which I can't share as it has too much sensitive information), and it's being used properly for the `upload_symbols` step as well as within the app itself.

**Comment by pwightman** [comment]
Also having this issue. I just followed these instructions when adding to my project: https://docs.bugsnag.com/build-integrations/fastlane/

Can confirm that @cwhenderson20's workaround of specifying the config file fixed it.

Unfortunately can't provide a minimal working example atm.

**Comment by mattdyoung** [comment]
@cwhenderson20 

Thanks for the additional details and the workaround. We'll re-open this and try to reproduce.

**Comment by mattdyoung** [comment]
@bgold0 @jaltin @cwhenderson20 @pwightman 

We've been trying to reproduce the behaviour you've been seeing. From what @cwhenderson20 stated, the `upload_symbols` lane appears to be able to read the API key from the `Info.plist` whereas the `send_build_to_bugsnag` lane fails with an apiKey not found error.

In our testing both lanes read the API key from the `Info.plist` successfully.

We've analyzed any differences in the 2 lanes to try and narrow down what could be causing the problem:
- The working `upload_symbols` lane allows the use of the `BUGSNAG_API_KEY` environment variable to populate the `apiKey` parameter. The non-working `send_build_to_bugsnag` lane does not. Do any of you have a `BUGSNAG_API_KEY` environment variable set as this could account for the difference.
- The working `upload_symbols` lane validates the apiKey when it's loaded from the config file, not during the run, which consists of checking it's 32 hex characters. The non-working `send_build_to_bugsnag` lane validates the apiKey before the payload delivery occurs which consists of checking it's not nil and is a String type. The disparity between these verifications may explain the difference.

Are you able to confirm whether either of these explanations could be the cause of what you're seeing?

**Comment by xander-jones** [comment]
Hey 👋 , we added a bunch of (optional) verbose debugging output to the `bugsnag-dsym-upload` tool in https://github.com/bugsnag/bugsnag-dsym-upload/releases/tag/v2.0.0. If you make your Fastlane call with the `--verbose` flag, you'll see a lot more info, including which `Info.plist` we're picking up (if any), and thus where the API key ought to be: https://docs.bugsnag.com/build-integrations/fastlane/#verbose-mode.

In addition to Matt's comment above, this might help us diagnose the issue if you could let us know the verbose output of this stage.

**Comment by xander-jones** [comment]
Closing this issue out as it's gone stale. Let us know if you have any follow up comments.
