### ISSUE TITLE
dSYM upload breaks when dSYM paths contain certain valid characters

### ISSUE THREAD

**Issue by jboulter11** [bugsnag/bugsnag-dsym-upload#40]
We (my coworker and I at Dropbox) ran into an issue with integrating with this plugin for submitting our dSYM paths to Bugsnag for the past two days.  I hope this can be fixed for future users and so we can remove the workaround from our ci for better performance and less maintenance.

### Expected behavior
a dSYM path that looks like the following should be uploaded without an error:
`/path/to/buck/module#apple-dsym,iphoneos-architecture.dSYM`

The `#` and `,` are valid characters in the APFS filesystem and should be accepted as paths.

### Observed behavior
Redactions surrounded by `< >`:
```
May  7 23:43:43.623: Preparing to upload /var/folders/<path>/<TargetName>Binary#apple-dsym,iphoneos-arm64.dSYM
May  7 23:43:43.637: Uploading UUID: <uuid> (arm64) /var/folders/<path>/<TargetName>Binary#apple-dsym,iphoneos-arm64.dSYM/Contents/Resources/DWARF/<TargetName>Binary
May  7 23:43:43.648: curl: (26) Failed to open/read local data from file/application
```

### Steps to reproduce
Try uploading a dSYM with a `#` or `,` inside the path and it should reproduce.

This is common notation for files produced by Buck, if I understand correctly.

### Version
1.4.2

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by phillipsam** [comment]
Hi @jboulter11 thanks for bringing this to our attention - we will look into this.

**Comment by xander-jones** [comment]
Hey @jboulter11, we've recently released https://github.com/bugsnag/bugsnag-dsym-upload/releases/tag/v2.1.0 of the `bugsnag-dsym-upload` tool which now handles these special characters when uploading dSYMs.
