### ISSUE TITLE
Skipping file without UUID errors?

### ISSUE THREAD

**Issue by pwightman** [bugsnag/bugsnag-dsym-upload#71]
### Describe the bug

Attempting to upload an `appDsyms.zip` file downloaded from App Store Connect is giving errors all of a sudden when it's worked fine before. Any advice?

### Steps to reproduce

Not sure what to specify here since it's specific to my app, and I can't upload it. See example code snippet below though.

### Environment

Version: 2.2.0

### Example code snippet

```
$ bugsnag-dsym-upload --api-key MY_KEY ~/Downloads/appDsyms.zip
```

Error message:

```
[ERROR] Skipping file without UUID: /var/folders/k_/hcmp1ytx47gbp_k1_y_p_1xw0000gn/T/bugsnag-dsym-upload.XXX.96vWPJUI/d69c5ca9-3f28-303f-b05c-343f14fd0273.dSYM/Contents/Resources/DWARF/MyApp
[ERROR] Skipping file without UUID: /var/folders/k_/hcmp1ytx47gbp_k1_y_p_1xw0000gn/T/bugsnag-dsym-upload.XXX.96vWPJUI/fcf9e7a3-b178-375f-946c-05219a8fe50f.dSYM/Contents/Resources/DWARF/MyAppExtension
2 file(s) failed to upload with errors
Re-run the bugsnag-dsym-upload tool with the --verbose option for more information
```

**Comment by luke-belton** [comment]
Hi @pwightman - this message is displayed if there is no matching UUID information in the file(s) at the specified path. As we match on UUID to symbolicate events,  if a UUID is not readable we don't upload the file at this stage.

If you're able to share the zip folder you're trying to upload with us at support@bugsnag.com we'd be happy to look into why this is failing.
