### ISSUE TITLE
Will it be saved automatically?

### ISSUE THREAD

**Issue by phonefixnicole** [bugsnag/bugsnag-dsym-upload#76]
### Description

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by johnkiely1** [comment]
Hi @phonefixnicole 

Would you be able to clarify the question your are asking as I'm not sure I understand what you are asking? 

Using the dSYM upload tool will upload dSYMs to Bugsnag. 

Alternatively you can check out our symbolication guide here: https://docs.bugsnag.com/platforms/ios/symbolication-guide/

**Comment by johnkiely1** [comment]
Closing this out due to lack of activity, happy to reopen as necessary.
